# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Dylan's Mini Blog.
paginate:       5
baseurl:        "/"
url:            "https://dylanchen0114.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Dylan Chen
  url:
  email:        dylanchen14@sina.com

# Custom vars
version:        3.4.1
github:
  repo:         https://dylanchen0114.github.io

# Gems
gems:
  - jekyll-paginate
